name: abstract_bloc
description: An abstract bloc with simplifies your life.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
